### ISSUE TITLE
please make a new release 

### ISSUE THREAD

**Issue by sergiomb2** [niltonvolpato/python-progressbar#56]

**Comment by muelli** [comment]
This is relevant for projects like Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=1282094

**Comment by toddrme2178** [comment]
This is an issue for openSUSE as well. A new release would be greatly appreciated.

**Comment by kparal** [comment]
@niltonvolpato any update here? The package is still not installable from pypi. Can you please release a new version?

**Comment by niltonvolpato** [comment]
I just published the 2.5 release to pypi. Sorry all for the delay, I wanted to to some more refactoring before publishing a new version, but the current repository version is good enough so I released that. Thanks!

https://pypi.org/manage/project/progressbar/release/2.5/

**Comment by kparal** [comment]
Thanks!

**Comment by sergiomb2** [comment]
the new link https://pypi.org/project/progressbar/#files
