### ISSUE TITLE
Python Progressbar cannot be installed

### ISSUE THREAD

**Issue by prathamesh321** [niltonvolpato/python-progressbar#58]
Even after giving the command "pip install progressbar", I get the following error as -

Collecting progressbar
         Could not fetch URL https://pypi.python.org/simple/progressbar/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) - skipping
        Could not find a version that satisfies the requirement progressbar (from versions: )
No matching distribution found for progressbar

What could be the issue?
An suggestions?

**Comment by niltonvolpato** [comment]
Actually I just published a new version to pypi. Can you try again?

https://pypi.org/manage/project/progressbar/release/2.5/
