### ISSUE TITLE
TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by danielmanu93** [niltonvolpato/python-progressbar#79]
Hi, I'm trying to use progress bar to display iteration progress on my data, but I get this error "TypeError: 'int' object is not iterable" as shown in the image below. From the image, the error indicates it's from line 240 of the progressbar.py module file. My progressbar code is also attached. How can I fix this?

![5](https://user-images.githubusercontent.com/67971334/121956671-a3750400-cd1e-11eb-898b-d74640f75a3f.jpeg)

![4](https://user-images.githubusercontent.com/67971334/121956679-a5d75e00-cd1e-11eb-8d9f-8280800ef1eb.jpeg)

**Comment by NiltonVolpato** [comment]
If you look at the __init__ method here:
https://github.com/niltonvolpato/python-progressbar/blob/3f63b2f974cbdea4484dfad38a5522d369450d01/progressbar/progressbar.py#L94
you are passing the equivalent of:
ProgressBar(maxval = 60, widgets = len(self.data))

So it's failing because you are passing a number as the argument widgets. You should fix the arguments you're passing.

**Comment by danielmanu93** [comment]
Thanks for the reply. So do you mean the widgets argument should be a list or ?

**Comment by NiltonVolpato** [comment]
Yeah, they should be a list. Or None to use the default. What did you intend by passing an integer as the widgets argument?

**Comment by danielmanu93** [comment]
Probably thought the widgets might also be a number since in the __init__ method, both have been assigned to None. And also I have tried assigning widgets=None, but I get a "value out of range error".
I'm not able to attach images since the issue has been closed but this is how it looks:
pr = progressbar.ProgressBar(60, widgets = None).start()
for i, mol in enumerate(self.data):
      data.append(mol)
pr.update(i + 1)

The error comes from the pr.update(i+1)
